version: '3'

services:
  patient-db:
    image: postgres:latest
    container_name: patient-db
    ports:
      - "5432:5432"
    
    environment:
      POSTGRES_USER: patientdb
      POSTGRES_PASSWORD: patient123
      POSTGRES_DB: patient-monitor
    networks:
      - postgres
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: amiinaliabdullaahi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: patient123
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    

networks:
    postgres:
      driver: bridge